title = "Comprehensive Gitleaks Configuration"
description = "Scans for common secrets, keys, and sensitive patterns"
version = 3

# Rules Section
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["key", "AWS"]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[A-Za-z0-9_]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-[0-9a-zA-Z]{10,48}'''
tags = ["key", "Slack"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api|apikey|secret|token)(.{0,20})?['\"][0-9a-zA-Z\-]{16,45}['\"]'''
tags = ["key", "generic"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN(?: RSA)? PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "jwt"
description = "JSON Web Token"
regex = '''eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9._-]{10,}\.[A-Za-z0-9._-]{10,}'''
tags = ["token", "JWT"]

[[rules]]
id = "password-variable"
description = "Hardcoded password in variable"
regex = '''(?i)(password|passwd|pwd)[\\s]*=[\\s]*["'].*["']'''
tags = ["password", "generic"]

[[rules]]
id = "ssh-password"
description = "SSH Password assignment"
regex = '''(?i)(sshpass|ssh_password|sshpassword)[\\s]*=[\\s]*["'].*["']'''
tags = ["password", "SSH"]

[[rules]]
id = "authorization-bearer"
description = "Authorization Bearer Token"
regex = '''(?i)authorization: *["']?Bearer [a-zA-Z0-9\-._~+/]+=*["']?'''
tags = ["token", "Authorization"]

# [allowlist] Section
[allowlist]
paths = [
  "\\.gitignore",
  "LICENSE",
  ".*\\.md"
]


# Allow known safe environment variables
envs = ["PATH", "NODE_ENV"]

# Allow safe commit authors or messages
commits = []
regexes = []
